#!/bin/sh

set -e

case "$1" in
    configure)
	# Xebian prefers legacy newt colors over Aubergine by default
	if update-alternatives --query newt-palette | grep -qs "Status: auto"; then
		update-alternatives --set newt-palette /etc/newt/palette.original
	fi
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#
exit 0
